Cuda            = True
seed            = 114514
distributed     = False
sync_bn         = False
fp16            = False
classes_path    = 'model_data/rtts_classes.txt'
anchors_path    = 'model_data/yolo_anchors.txt'
anchors_mask    = [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
model_path      = 'model_data/yolov7_tiny_weights.pth'
input_shape     = [640, 640]
pretrained      = False
Init_Epoch          = 0
Freeze_Epoch        = 100
Freeze_batch_size   = 16
UnFreeze_Epoch      = 300
Unfreeze_batch_size = 16
Freeze_Train        = True
Init_lr             = 1e-2
Min_lr              = Init_lr * 0.01
optimizer_type      = "sgd"
momentum            = 0.937
weight_decay        = 5e-4
lr_decay_type       = "cos"
save_period         = 10
save_dir            = 'logs'
eval_flag           = True
eval_period         = 10
num_workers         = 0
train_annotation_path   = '2007_train_fog.txt' 
val_annotation_path     = '2007_val_fog.txt'
clear_annotation_path = '2007_train.txt'